// import React from 'react';
import Head from 'next/head';
import styles from '@/styles/home.module.css';
import Login from '@/components/login';
import ImageSlider from '@/components/ImageSlider';


export default function Home() {
  return (

    <>
      <Head>
        <title>Instagram Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/insta.favicon.ico" />
      </Head>

     <main className={`${styles.main}`}>   
     <Login/>

     <ImageSlider/>
     </main>

     </>

     )
  };

